### ISSUE TITLE
Sensitivity: show percentage of masked data in the title

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/bondia#101]
@saurabh-astro Do you mean the flag mask only, or also the rfi mask? Is this not too specific to be part of the title?

Do you want this for the ringmap, too?
Should this include nan's already in the data?

**Comment by saurabh-astro** [comment]
While going through the plots, it would have been nice to compare how much data we had flagged, and compare that against some baseline level. Some indication of what fraction of the data was flagged for that day due to RFI would be useful, not necessarily in the title, if it seems too specific there.

**Comment by nritsche** [comment]
Okay, so that's simply the count of rfi masked indices divided by the size of the map? I'll find a place where to put that.

**Comment by saurabh-astro** [comment]
Yeah, that would be helpful.

**Comment by nritsche** [comment]
`round(np.count_nonzero(rfi_mask) / measured_sensitivity.size * 100)`

![bokeh_plot](https://user-images.githubusercontent.com/2536635/101226115-49490700-3648-11eb-8aa7-eaebf148a190.jpeg)
